name: npm publish release
on: 
  push:
    branches:
      - "main"
    paths:
      - "package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13.0"
      - run: |
         npm i
         npm run build
      - name: publish npm 
        uses: JS-DevTools/npm-publish@v1
        with:
          tag: latest
          package: dist/package.json
          token: ${{ secrets.NPM_TOKEN }}