name: npm publish beta
on: 
  push:
    branches:
      - "dev"
    paths:
        - "package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13.0"
      - name: check version is beta and package 
      - run: |
         node scripts/check.js beta
         npm i
         npm run build
      - name: publish npm 
        uses: JS-DevTools/npm-publish@v1
        with:
          tag: beta
          package: dist/package.json
          token: ${{ secrets.NPM_TOKEN }}